version: '3.4'
services:
  redis-cluster:
    image: "grokzen/redis-cluster:latest"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
    environment:
      IP: 0.0.0.0
  mongo:
    image: "circleci/mongo:4.0.1"
    ports:
      - "27017:27017"
  memcached:
    image: "memcached:1.5.20-alpine"
    ports:
      - "11211:11211"
  redis:
    image: "circleci/redis"
    ports:
      - "6379:6379"
  mysql:
    image: "circleci/mysql:5.7"
    #network_mode: host
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: getalife
      MYSQL_DATABASE: local